# Generated by Django 5.1.1 on 2024-10-09 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_category_product_categorysub'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysub',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
