# Generated by Django 5.1.1 on 2024-10-10 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_customer_pad'),
        ('shop', '0004_categorysub_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
