# Generated by Django 5.1.1 on 2024-10-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
