# Generated by Django 5.1.1 on 2024-10-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysub',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
