# Generated by Django 5.1.1 on 2024-10-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pictuer',
            new_name='picture',
        ),
    ]
