# Generated by Django 5.1.1 on 2024-12-01 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysub',
            old_name='key',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
