# Generated by Django 5.1.1 on 2024-12-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال پردازش'), ('Shipped', '  ارسال شده به پست'), ('Delivered', 'تحویل داده شده')], default='Pending', max_length=50),
        ),
    ]
