# Generated by Django 5.1.1 on 2024-10-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pad',
        ),
    ]
