# Generated by Django 5.1.1 on 2024-12-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_phon_customer_phone_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
